### ISSUE TITLE
Bot stops playing after heroku restarts it

### ISSUE THREAD

**Issue by SnGmng** [helionmusic/rhinobot_heroku#26]
**Describe the problem**
Bot stops playing after heroku executes a sceduled restart once a day. You have to restart the bot manually again to make it play. 

**Have you followed all the instructions?**
yes
**Tried updating the dependencies?**
yes

**Bot version**
newest. but this issue applies to (almost) all versions (i have this issue for like 6-12months)

**Comment by codeinteger6** [comment]
If Heroku restarts the bot while it's in the voice channel, the only solution is to disconnect and reconnect the bot to the voice channel. Unfortunately this is a Discord issue and the same thing happens if I run the bot on my own PC using the official instructions.

Since the official devs don't really support Heroku there isn't really much that can be done about it. You will have to keep the bot out of the voice channel when you're not using it or let your server members know that if this happens, to use the disconnect command and then summon the bot again.

**Comment by codeinteger6** [comment]
Gonna pin this as it may be a common thing people will open an issue for

**Comment by SnGmng** [comment]
Well then it might be possible to make the musicbot disconnect and reconnect automatically if it is in a voice channel on startup. Shouldnt take too long to fix, im gonna look into it.

**Comment by codeinteger6** [comment]
> Well then it might be possible to make the musicbot disconnect and reconnect automatically if it is in a voice channel on startup. Shouldnt take too long to fix, im gonna look into it.

Feel free to make a pull request if you manage to fix it 🙂

**Comment by SnGmng** [comment]
Look at line 425 in this method:
https://github.com/helionmusic/rhinobot_heroku/blob/c93de45a1f65acbadb1de72ce9eb63b70fb87b4c/musicbot/bot.py#L414-L439
Im not very familiar with the code but commenting out line 425 will probably fix the issue. If i want to test my assumtion i would have to setup a whole new bot so if you have a bot, can you test if it works? 😄

**Comment by codeinteger6** [comment]
> Look at line 425 and 424 in this method:
> 
> https://github.com/helionmusic/rhinobot_heroku/blob/c93de45a1f65acbadb1de72ce9eb63b70fb87b4c/musicbot/bot.py#L414-L439
> 
> 
> Im not very familiar with the code but commenting out line 425 will probably fix the issue. If i want to test my assumtion i would have to setup a whole new bot so if you have a bot, can you test if it works? 😄

Will test it tomorrow.

**Comment by codeinteger6** [comment]
@SnGmng nope doesn't work

**Comment by SnGmng** [comment]
I've found the solution 😄 . Gonna make a PR soon

**Comment by codeinteger6** [comment]
Thanks a lot! I merged your PR.
