### ISSUE TITLE
[Suggstion]

### ISSUE THREAD

**Issue by TheFatalKiller** [helionmusic/rhinobot_heroku#32]
A command where it blacklists the certain user that is mentioned from using the bot for example !blacklist (user)

**Comment by codeinteger6** [comment]
There already is a blacklist command, but it is useless for Heroku as when the bot restarts every 24 hours due to Heroku policy, the blacklist settings will be lost. You will have to block users from using the bot manually by editing the permissions.ini file.

Also, we don't accept feature requests. Our only job is to make the bot work on Heroku.
