### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by Smixite** [helionmusic/rhinobot_heroku#36]
**Describe the problem** 
Having a Bot Token authentication error, despite following all the steps
**Have you followed all the instructions?** 
- [X ] Yes, I followed the instructions properly.

**Tried updating the dependencies?** 
- [X ] Yes, they are up to date.
- [ ] Not applicable for this issue.

**260819** <!-- Please let us know the release version of the bot you are using.

**Comment by helionmusic** [comment]
You were able to correct the issue?

**Comment by Smixite** [comment]
Yes. Thanks for the help

**Comment by Smixite** [comment]
But I currently met with a issue. Where music won't start

**Comment by Smixite** [comment]
But I currently met with a issue. Where music won't start

**Comment by codeinteger6** [comment]
Is there any error message?

**Comment by Smixite** [comment]
No error messages

**Comment by codeinteger6** [comment]
What do the logs say in Heroku?

**Comment by codeinteger6** [comment]
This is apparently a problem in discord.py, due to changes in Discord.

![image](https://user-images.githubusercontent.com/44692189/66915644-51f10f00-f03b-11e9-991b-ad1a55183a51.png)

We will try and figure out how we can get solution 1 working in Heroku. If you don't mind waiting you can wait for discord.py to push a new release in GitHub and update the dependencies normally.

Anyone is welcome to submit a PR if they manage to get theirs working.

**Comment by codeinteger6** [comment]
@Smixite, I may have found a solution, please check the readme in this repo, scroll down to the updating youtube-dl section, and copy paste the example format in your requirements.txt file and push it to Heroku.

If it still doesn't work, try deleting and remaking the Heroku application.

**Comment by Smixite** [comment]
The solution works! Thanks for the help
